imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: ru

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

doctrine_mongodb:
    connections:
        default:
            server: "%mongo_server%"
    default_database: "%mongo_database%"
    document_managers:
        default:
            auto_mapping: true

sensio_framework_extra:
   router:
        annotations: false

knp_paginator:
    default_options:
        sort_field_name: sortField
        sort_direction_name: sortDirection

sirian_suggest:
    form_options:
        widget: select2_v4
        attr:
            placeholder: "Поиск..."
    odm:
        question:
            class: AdminBundle:Question
            property: title
            search:
                title: ~
        question_tag:
                    class: AdminBundle:QuestionTag
                    property: name
                    search:
                        name: ~