security:
    encoders:
        App\AdminBundle\Document\User: sha512
    providers:
        username_or_email:
            id: 'App\AdminBundle\Security\UserProvider'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: admin_dashboard
                remember_me: true
            remember_me:
                secret: "%secret%%secret%"
                domain: ".%base_host%"
                always_remember_me: true
    access_control:
        - { path: ^/(login|register|recover), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
