security:
    encoders:
        App\MainBundle\Document\User: sha512
    providers:
        username_or_email:
            id: 'App\AdminBundle\Security\UserProvider'
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            host: "^(%base_host%)$"
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                remember_me: true
            remember_me:
                secret: "%secret%%secret%"
                domain: ".%base_host%"
                always_remember_me: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
