admin_question_edit:
    path: /{id}/edit
    defaults:
        _controller: AdminBundle:Question:edit

admin_question_new:
    path: /new
    defaults:
        _controller: AdminBundle:Question:new

admin_question_list:
    path: /list
    defaults:
        _controller: AdminBundle:Question:list

admin_question_form:
    path: /form
    defaults:
        _controller: AdminBundle:Question:form

admin_question_suggest_form:
    path: /suggest-form
    defaults:
        _controller: AdminBundle:Question:suggestForm

admin_question_add_to_interview:
    path: /{id}/add
    defaults:
        _controller: AdminBundle:Question:addToInterview

admin_question_add_to_interview_from_bank:
    path: /{id}/add-from-bank
    defaults:
        _controller: AdminBundle:Question:addToInterviewFromBank