admin_dashboard:
    path: /
    defaults:
        _controller: AdminBundle:Dashboard:index

_admin_interview:
    prefix: /interview
    resource: routing/interview.yml

_admin_question:
    prefix: /question
    resource: routing/question.yml

_admin_question_tag:
    prefix: /question_tag
    resource: routing/question_tag.yml

_admin_region:
    prefix: /region
    resource: routing/region.yml

_admin_legal_entity:
    prefix: /legal-entity
    resource: routing/legal_entity.yml

login:
    path: /login
    defaults:
        _controller: AdminBundle:Security:login

login_check:
    path: /login_check
    defaults:
        _controller: AdminBundle:Security:/loginCheck

logout:
    path: /logout
    defaults:
        _controller: AdminBundle:Security:logout

_api_interview:
    prefix: /api
    resource: routing/api.yml