admin_dashboard:
    path: /
    defaults:
        _controller: AdminBundle:Dashboard:index

_admin_poll:
    prefix: /poll
    resource: routing/poll.yml

login:
    path: /login
    defaults:
        _controller: AdminBundle:Security:login