admin_dashboard:
    path: /
    defaults:
        _controller: AdminBundle:Dashboard:index

_admin_poll:
    prefix: /poll
    resource: routing/poll.yml

_admin_question:
    prefix: /question
    resource: routing/question.yml

login:
    path: /login
    defaults:
        _controller: AdminBundle:Security:login

login_check:
    path: /login_check
    defaults:
        _controller: AdminBundle:Security:/loginCheck

logout:
    path: /logout
    defaults:
        _controller: AdminBundle:Security:logout